### PR TITLE
WIP: Trying to support exporting of all fields

### PR DESCRIPTION
**Pull request by jjshoe**

### CODE REVIEW

**Comment by jjshoe** [comment]
Very close, when I run this, I get something like the following:

```
[
  {
    "id": "5901808332069094454",
    "name": "Bob",
    "fullname": "Bob",
    "username": "bbob",
    "password": "qwerty",
    "last_modified_gmt": "1617366516",
    "last_touch": "0",
    "group": "",
    "url": "http://test.com",
    "note": "",
    "fields": [
      "foo": "bar" 
unhandled type: -5446576
      {
        "id": "5901808332069094454",
        "name": "Bob",
        "fullname": "Bob",
        "username": "bbob",
        "password": "qwerty",
        "last_modified_gmt": "1617366516",
        "last_touch": "0",
        "group": "",
        "url": "http://test.com",
        "note": "",
        "fields": [
          "foo": "bar" 
unhandled type: -5446576
          {
            "id": "5901808332069094454",
            "name": "Bob",
            "fullname": "Bob",
            "username": "bbob",
            "password": "qwerty",
            "last_modified_gmt": "1617366516",
            "last_touch": "0",
            "group": "",
            "url": "http://test.com",
            "note": "",
            "fields": [
              "foo": "bar" 
unhandled type: -5446576
```

**Comment by msdrigg** [comment]
I am also not a c developer, but I support the work. I am looking for a tool that does exactly like this.

I'll take a look and see if there's anything I can help with

**Comment by waterkip** [comment]
I'm sorry, I don't actively use github and I didn't configure this repo properly so I didn't get all the updates. I have now :)

In any case, your PR still seems to be WIP, so I won't include it into the fork. Also I do require you to sign-off the commits. I would also advise you to rebase, as I see a merge commit in your PR.

**Comment by 0xdevalias** [comment]
> A few (unverified) PR's from the original repo that might be relevant/related/useful here:
> 
> - https://github.com/lastpass/lastpass-cli/pull/572
> - https://github.com/lastpass/lastpass-cli/pull/573
> - https://github.com/lastpass/lastpass-cli/pull/574
> - https://github.com/lastpass/lastpass-cli/pull/614
> - https://github.com/lastpass/lastpass-cli/pull/628
> 
> _Originally posted by @0xdevalias in https://github.com/lastpass-cli-fork/lastpass-cli/issues/1#issuecomment-1384548095_

**Pull request closed without merging**
